# Generated by Django 3.2.7 on 2021-09-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_reviewrating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='store',
            name='trader_license',
            field=models.ImageField(blank=True, default='', upload_to='images/stores/licenses'),
        ),
    ]
