# Generated by Django 3.2.6 on 2021-08-29 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_address_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='fullname',
        ),
    ]
