# Generated by Django 3.2.7 on 2021-09-15 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Open', 'Open')], default='Open', max_length=50)),
                ('ticket_type', models.CharField(choices=[('Website problem', 'Website problem'), ('Info inquiry', 'Info inquiry'), ('Complaint', 'Complaint')], default='Info inquiry', max_length=50)),
                ('priority', models.CharField(choices=[('Urgent', 'Urgent'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Low', max_length=50)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('ticket_file', models.ImageField(blank=True, upload_to='images/tickets/files/%Y/%m/%d/')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
