# Generated by Django 3.2.6 on 2021-08-28 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_order_tax'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='Store',
            new_name='store',
        ),
    ]
